### ISSUE TITLE
 NonError: Event { isTrusted: [Getter] } on Catalina on 10.15.4

### ISSUE THREAD

**Issue by maxacarvalho** [forged-ui/support#1]
Once I click in any website I get several error messages like https://share.getcloudapp.com/nOuN4zkP

**Comment by OwenMelbz** [comment]
Hi @maxacarvalho 

Did you download one of the prebuilt binaries or compile it yourself?

I would say currently we display all "errors" some of them are not actually errors - they're just Promises which are throwing rejections to help identify issues.

Many of them won't effect the functionality.

---

That being said...

Are you able to provide a screen recording or an exactly whats happening? I've just tested the latest build on macOs Catalina and unable to replicate this, so there must be something else going on.

I'm wondering if theres something specific with your site configurations that need to fix.

If you use Chrome you can install [this free extension](https://www.screencastify.com/) which records desktop applications and uploads them automatically incase you havent got anything like that, then you can share me the link to progress.

---

If your compiling your own builds, I've just uploaded a new one to the drive link, which you can download and try.

**Comment by maxacarvalho** [comment]
Hi @OwenMelbz 

I downloaed the pre-built binary.

I'm on macOs Catalina 10.15.4

here's the screen recording https://share.getcloudapp.com/KouWRzyZ

**Comment by OwenMelbz** [comment]
Hi,

Thanks for that it's really helpful. 

It looks like it's specifically to do with the new WYSIWYG editor - I'll give this a look as to what it could be.

I'm on Catalina 10.15.3 so I'll update and see if that makes a difference thanks.

**Comment by OwenMelbz** [comment]
Hi @maxacarvalho 

I've just updated and can confirm the bug is something to do with the latest Catalina update.

I'll get onto fixing this as soon as possible, I'm feeling it might be related to an electron update.

Please hold with me.

Thanks

**Comment by OwenMelbz** [comment]
Hi @maxacarvalho 

I've just overwritten the existing file in the drive with a new version.

Could you please try this and let me know how you get on with it?

Thanks

**Comment by maxacarvalho** [comment]
@OwenMelbz 

Now it seems to be better, but I still get an error message (see below).

Screen recording: https://share.getcloudapp.com/P8uRKGEG

```
Unhandled Promise Rejection
Error: Request failed with status code 404
    at e.exports (/Applications/Forged UI.app/Contents/Resources/app.asar/dist/renderer.prod.js:2:867481)
    at e.exports (/Applications/Forged UI.app/Contents/Resources/app.asar/dist/renderer.prod.js:2:868928)
    at XMLHttpRequest.p.onreadystatechange (/Applications/Forged UI.app/Contents/Resources/app.asar/dist/renderer.prod.js:2:863249)
    at XMLHttpRequest.r (/Applications/Forged UI.app/Contents/Resources/app.asar/dist/renderer.prod.js:2:27793)
```

**Comment by OwenMelbz** [comment]
Hi,

The 404 looks like it’s come back from Laravel Forge itself!

I’m wondering have you deployed anything yet? I’m guessing Forge is saying you don’t have a deployment log yet

**Comment by maxacarvalho** [comment]
Hi @OwenMelbz 

What I have in place is a few security stuff, for example, nobody can reach my website without passing through Cloudflare, for that, I have blocked the HTTP and HTTPS traffic for direct traffic, you cannot reach by IP address for example, must go through the domain.

That above said, I just added inbound rules allowing Forge's IP addresses and my current IP address, but I still get the errors mentioned above, so I don't know what route your app is taking to communicate.

Perhaps if you explain the flow to me I can give you more insights.

**Comment by OwenMelbz** [comment]
The app doesn’t communicate with your server or website in anyway so Cloudflare is okay.

We just use the Laravel Forge API: https://forge.laravel.com/api-documentation so we don’t need any access or visibility of your website.

When you login to Laravel Forge on the website, and go into your site on their.

Does your deployment log show anything?

**Comment by maxacarvalho** [comment]
@OwenMelbz ok, so the problem seems to be with the lack of deployment logs.
For example, I do not use Forge to deploy my production sites, so no deployment log will be generated.

I just tested a deployment with one testing domain, after that the Forge UI worked as expected.

I believe you have to take that into account, make sure you check for _non-standard_ Forge deployments, etc. When you need a file that might not be there is better to run a quick check.

**Comment by OwenMelbz** [comment]
Hi Max,

Just to let you know theres a new version to download from drive which prevents the 404 errors in deployments.

Thanks
